version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: okianus_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: okianus
      POSTGRES_PASSWORD: okianus2026
      POSTGRES_DB: okianus_db
    ports:
      - '5432:5432'
    volumes:
      - okianus_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U okianus -d okianus_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  okianus_pgdata:
    driver: local
